version: '3'

services:
  app-nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    links:
      - app-fpm

  app-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    links:
      - mysql

  app-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  mysql:
